"""ajout champ actif sur produit

Revision ID: 137c9f3dcdd3
Revises: 24f8061953c3
Create Date: 2026-08-23 09:44:20.779740

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '137c9f3dcdd3'
down_revision: Union[str, Sequence[str], None] = '24f8061953c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('produits', sa.Column('actif', sa.Boolean(), nullable=False, server_default=sa.text('1')))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('produits', 'actif')
    # ### end Alembic commands ###
