"""creation tables initiales

Revision ID: 24f8061953c3
Revises: 
Create Date: 2026-08-21 20:39:11.268650

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24f8061953c3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nom')
    )
    op.create_index(op.f('ix_categories_id'), 'categories', ['id'], unique=False)
    op.create_index(op.f('ix_categories_slug'), 'categories', ['slug'], unique=True)
    op.create_table('utilisateurs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_utilisateurs_email'), 'utilisateurs', ['email'], unique=True)
    op.create_index(op.f('ix_utilisateurs_id'), 'utilisateurs', ['id'], unique=False)
    op.create_table('commandes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('statut', sa.String(), nullable=False),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('utilisateur_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commandes_id'), 'commandes', ['id'], unique=False)
    op.create_table('produits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('prix', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('categorie_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['categorie_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_produits_id'), 'produits', ['id'], unique=False)
    op.create_index(op.f('ix_produits_nom'), 'produits', ['nom'], unique=False)
    op.create_table('avis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('note', sa.Integer(), nullable=False),
    sa.Column('commentaire', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('produit_id', sa.Integer(), nullable=False),
    sa.Column('utilisateur_id', sa.Integer(), nullable=False),
    sa.Column('commande_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['commande_id'], ['commandes.id'], ),
    sa.ForeignKeyConstraint(['produit_id'], ['produits.id'], ),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_avis_id'), 'avis', ['id'], unique=False)
    op.create_table('lignes_commande',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quantite', sa.Integer(), nullable=False),
    sa.Column('prix_unitaire', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('commande_id', sa.Integer(), nullable=False),
    sa.Column('produit_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['commande_id'], ['commandes.id'], ),
    sa.ForeignKeyConstraint(['produit_id'], ['produits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lignes_commande_id'), 'lignes_commande', ['id'], unique=False)
    op.create_table('paiements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('statut', sa.String(), nullable=False),
    sa.Column('methode', sa.String(), nullable=False),
    sa.Column('reference_simulee', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('commande_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['commande_id'], ['commandes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('commande_id')
    )
    op.create_index(op.f('ix_paiements_id'), 'paiements', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_paiements_id'), table_name='paiements')
    op.drop_table('paiements')
    op.drop_index(op.f('ix_lignes_commande_id'), table_name='lignes_commande')
    op.drop_table('lignes_commande')
    op.drop_index(op.f('ix_avis_id'), table_name='avis')
    op.drop_table('avis')
    op.drop_index(op.f('ix_produits_nom'), table_name='produits')
    op.drop_index(op.f('ix_produits_id'), table_name='produits')
    op.drop_table('produits')
    op.drop_index(op.f('ix_commandes_id'), table_name='commandes')
    op.drop_table('commandes')
    op.drop_index(op.f('ix_utilisateurs_id'), table_name='utilisateurs')
    op.drop_index(op.f('ix_utilisateurs_email'), table_name='utilisateurs')
    op.drop_table('utilisateurs')
    op.drop_index(op.f('ix_categories_slug'), table_name='categories')
    op.drop_index(op.f('ix_categories_id'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
