"""ajout tailles et images produit

Revision ID: d47fadef6a8b
Revises: 137c9f3dcdd3
Create Date: 2026-08-23 11:37:40.204106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd47fadef6a8b'
down_revision: Union[str, Sequence[str], None] = '137c9f3dcdd3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tailles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nom')
    )
    op.create_index(op.f('ix_tailles_id'), 'tailles', ['id'], unique=False)
    op.create_table('images_produit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('produit_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('ordre', sa.Integer(), nullable=False),
    sa.Column('est_principale', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['produit_id'], ['produits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_images_produit_id'), 'images_produit', ['id'], unique=False)
    op.create_table('produits_tailles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('produit_id', sa.Integer(), nullable=False),
    sa.Column('taille_id', sa.Integer(), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['produit_id'], ['produits.id'], ),
    sa.ForeignKeyConstraint(['taille_id'], ['tailles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('produit_id', 'taille_id', name='uq_produit_taille')
    )
    op.create_index(op.f('ix_produits_tailles_id'), 'produits_tailles', ['id'], unique=False)
    op.drop_column('produits', 'stock')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('produits', sa.Column('stock', sa.INTEGER(), nullable=False))
    op.drop_index(op.f('ix_produits_tailles_id'), table_name='produits_tailles')
    op.drop_table('produits_tailles')
    op.drop_index(op.f('ix_images_produit_id'), table_name='images_produit')
    op.drop_table('images_produit')
    op.drop_index(op.f('ix_tailles_id'), table_name='tailles')
    op.drop_table('tailles')
    # ### end Alembic commands ###
